from __future__ import annotations

import sys
from dataclasses import dataclass, fields, replace
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib  # type: ignore

DEFAULT_WORDS = 350
DEFAULT_IMAGES = "none"
DEFAULT_INDEX_TITLE = "EPUB Library"
DEFAULT_NODE_NAME = "EPUB Library"
DEFAULT_DESCRIPTION = "Public bookshelf. No login required."
DEBOUNCE_SECONDS = 2.0
DEFAULT_CONFIG_NAME = "nomadnet-epub.toml"

SAMPLE_CONFIG = """\
# nomadnet-epub.toml — single config for this tool.
# index_title: heading on index.mu
# node_name: NomadNet announce / network display name
# description: tagline under the heading on index.mu

index_title = "EPUB Library"
description = "Public bookshelf. No login required."
node_name = "EPUB Library"

epubs = "./epubs"
data_dir = "./data/nomadnetwork"
words = 350
images = "none"   # or "files"
"""

MINIMAL_NOMADNET_CONFIG = """\
# Generated by nomadnet-epub — node_name synced from nomadnet-epub.toml on serve.

[logging]
loglevel = 4
destination = file

[client]
enable_client = yes
user_interface = text
announce_at_start = yes
announce_interval = 360
try_propagation_on_send_fail = yes
periodic_lxmf_sync = yes
lxmf_sync_interval = 360
lxmf_sync_limit = 8

[textui]
intro_time = 1
theme = dark
colormode = 256

[node]
enable_node = yes
node_name = {node_name}
announce_interval = 360
announce_at_start = Yes
disable_propagation = Yes
"""

TEXTUI_SECTION = """\

[textui]
intro_time = 1
theme = dark
colormode = 256
"""


@dataclass
class Settings:
    epubs_dir: Path
    data_dir: Path
    words: int = DEFAULT_WORDS
    images: str = DEFAULT_IMAGES
    index_title: str = DEFAULT_INDEX_TITLE
    node_name: str = DEFAULT_NODE_NAME
    description: str = DEFAULT_DESCRIPTION
    config_path: Path | None = None

    @property
    def nomad_config_dir(self) -> Path:
        return self.data_dir

    @property
    def pages_dir(self) -> Path:
        return self.data_dir / "storage" / "pages"

    @property
    def files_dir(self) -> Path:
        return self.data_dir / "storage" / "files"

    @property
    def books_pages_dir(self) -> Path:
        return self.pages_dir / "books"

    @property
    def books_files_dir(self) -> Path:
        return self.files_dir / "books"

    @property
    def state_path(self) -> Path:
        return self.data_dir / "epub_state.json"


def default_config_path() -> Path:
    return Path.cwd() / DEFAULT_CONFIG_NAME


def _quote_config_value(value: str) -> str:
    if not value:
        return '""'
    if all(c.isalnum() or c in "-_" for c in value):
        return value
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def write_sample_config(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(SAMPLE_CONFIG, encoding="utf-8")
    return path


def load_toml(path: Path) -> dict:
    with path.open("rb") as f:
        return tomllib.load(f)


def settings_from_file(path: Path, *, cwd: Path | None = None) -> Settings:
    cwd = cwd or Path.cwd()
    data = load_toml(path)
    base = path.parent

    def resolve(key: str, default: str) -> Path:
        raw = data.get(key, default)
        p = Path(str(raw)).expanduser()
        if not p.is_absolute():
            p = (base / p).resolve()
        else:
            p = p.resolve()
        return p

    images = str(data.get("images", DEFAULT_IMAGES))
    if images not in ("none", "files"):
        raise ValueError(f"config images must be 'none' or 'files', got {images!r}")

    # Legacy: old configs used node_name for the index header too
    legacy_title = data.get("node_name", DEFAULT_INDEX_TITLE)
    index_title = str(data.get("index_title", legacy_title))
    node_name = str(data.get("node_name", DEFAULT_NODE_NAME))

    return Settings(
        epubs_dir=resolve("epubs", str(cwd / "epubs")),
        data_dir=resolve("data_dir", str(cwd / "data" / "nomadnetwork")),
        words=int(data.get("words", DEFAULT_WORDS)),
        images=images,
        index_title=index_title,
        node_name=node_name,
        description=str(data.get("description", DEFAULT_DESCRIPTION)),
        config_path=path.resolve(),
    )


def merge_cli_overrides(settings: Settings, **overrides) -> Settings:
    """Apply non-None CLI overrides on top of file/default settings."""
    updates = {k: v for k, v in overrides.items() if v is not None}
    valid = {f.name for f in fields(Settings)}
    updates = {k: v for k, v in updates.items() if k in valid}
    return replace(settings, **updates)


def ensure_dirs(settings: Settings) -> None:
    settings.epubs_dir.mkdir(parents=True, exist_ok=True)
    settings.pages_dir.mkdir(parents=True, exist_ok=True)
    settings.files_dir.mkdir(parents=True, exist_ok=True)
    settings.books_pages_dir.mkdir(parents=True, exist_ok=True)
    settings.books_files_dir.mkdir(parents=True, exist_ok=True)


def _sync_node_name(config_text: str, node_name: str) -> str:
    import re

    quoted = _quote_config_value(node_name)
    if re.search(r"(?m)^node_name\s*=", config_text):
        return re.sub(
            r"(?m)^node_name\s*=\s*.*$",
            f"node_name = {quoted}",
            config_text,
            count=1,
        )
    if "[node]" in config_text:
        return config_text.replace(
            "[node]", f"[node]\nnode_name = {quoted}", 1
        )
    return config_text


def ensure_nomad_config(settings: Settings) -> Path:
    """Create/sync NomadNet runtime config from nomadnet-epub.toml node_name."""
    config_path = settings.nomad_config_dir / "config"
    settings.nomad_config_dir.mkdir(parents=True, exist_ok=True)
    (settings.nomad_config_dir / "storage" / "pages").mkdir(parents=True, exist_ok=True)
    (settings.nomad_config_dir / "storage" / "files").mkdir(parents=True, exist_ok=True)
    quoted = _quote_config_value(settings.node_name)
    if not config_path.exists():
        config_path.write_text(
            MINIMAL_NOMADNET_CONFIG.format(node_name=quoted),
            encoding="utf-8",
        )
    else:
        text = config_path.read_text(encoding="utf-8")
        if "user_interface" in text and "[textui]" not in text:
            text = text.rstrip() + TEXTUI_SECTION
        text = _sync_node_name(text, settings.node_name)
        config_path.write_text(text, encoding="utf-8")
    return settings.nomad_config_dir
